In [1]:
%pip install ipytest -q
%pip install ipytest -q

import numpy as np
import ipytest
import pytest

ipytest.autoconfig()
np.matrix

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


numpy.matrix

In [2]:
class Matrix:
    def __init__(self, matrix):
        self.matrix = matrix
        
    
    def __add__(self, other):
        if isinstance(other, Matrix) and self._is_same_shape(other):
            ans = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(self.matrix[i])):
                    row.append(self.matrix[i][j] + other.matrix[i][j])
                ans.append(row)
            return Matrix(ans)
        else:
            raise ValueError("ошибка")
            
    def __sub__(self, other):
        if isinstance(other, Matrix) and self._is_same_shape(other):
            ans = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(self.matrix[i])):
                    row.append(self.matrix[i][j] - other.matrix[i][j])
                ans.append(row)
            return Matrix(ans)
        else:
            raise ValueError("Ошибка")
            
    def __mul__(self, other):
        if isinstance(other, Matrix) and self._is_same_multiplication_shape(other):
            ans = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(other.matrix[0])):
                    element = 0
                    for k in range(len(other.matrix)):
                        element += self.matrix[i][k] * other.matrix[k][j]
                    row.append(element)
                ans.append(row)
            return Matrix(ans)
        elif isinstance(other, (int, float)):
            ans = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(self.matrix[i])):
                    row.append(self.matrix[i][j] * other)
                ans.append(row)
            return Matrix(ans)
        else:
            raise ValueError("Ошибка")
           
    def __truediv__(self, other):
        if isinstance(other, (int, float)):
            ans = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(self.matrix[i])):
                    row.append(self.matrix[i][j] / other)
                ans.append(row)
            return Matrix(ans)
        else:
            raise ValueError("Ошибка")
            
    def __matmul__(self, other):
        if isinstance(other, Matrix) and self._is_same_multiplication_shape(other):
            ans = []
            for i in range(len(self.matrix)):
                row = []
                for j in range(len(other.matrix[0])):
                    element = 0
                    for k in range(len(other.matrix)):
                        element += self.matrix[i][k] * other.matrix[k][j]
                    row.append(element)
                ans.append(row)
            return Matrix(ans)
        else:
            raise ValueError("Ошибка")
    
    def T(self):
        ans = []
        for j in range(len(self.matrix[0])):
            row = []
            for i in range(len(self.matrix)):
                row.append(self.matrix[i][j])
            ans.append(row)
        return Matrix(ans)
    
    def _is_same_shape(self, other):
        return len(self.matrix) == len(other.matrix) and len(self.matrix[0]) == len(other.matrix[0])
    
    def _is_same_multiplication_shape(self, other):
        return len(self.matrix[0]) == len(other.matrix)


In [3]:
%%ipytest
import numpy as np

matrix1 = Matrix([[1,2,3],[1,2,3],[1,2,3]])
matrix2 = Matrix([[4,5,6],[4,5,6],[4,5,6]])

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_add_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (np.array((matrix1 + matrix2).matrix) == (np.array(matrix1.matrix) + np.array(matrix2.matrix))).all()
    ), 'add section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13.2]])
def test_matrix_add_number(matrix1: Matrix, number: int | float):
    assert (
        (np.array((matrix1 + number).matrix) == np.array(matrix1.matrix) + number).all()
    ), 'add section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_sub_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (np.array((matrix1 - matrix2).matrix) == np.array(matrix1.matrix) - np.array(matrix2.matrix)).all()
    ), 'sub section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 12.2]])    
def test_matrix_sub_number(matrix1: Matrix, number: int | float):
    assert (
        (np.array((matrix1 - number).matrix) == np.array(matrix1.matrix) - number).all()
    ), 'sub section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1", [matrix1])    
def test_matrix_transpose(matrix1: Matrix):
    assert (
        (np.array(matrix1.T().matrix) == np.array(matrix1.matrix).T).all()
    ), 'transpose section is not working right'
    
# -----------------------------------------

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_mul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (np.array((matrix1 * matrix2).matrix) == np.array(matrix1.matrix) * np.array(matrix2.matrix)).all()
    ), 'mul section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13]])
def test_matrix_mul_number(matrix1: Matrix, number: int | float):
    assert (
        (np.array((matrix1 * number).matrix) == np.array(matrix1.matrix) * number).all()
    ), 'mul section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])    
def test_matrix_div_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (np.array((matrix1 / matrix2).matrix) == np.array(matrix1.matrix) / np.array(matrix2.matrix)).all()
    ), 'div section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 2]])    
def test_matrix_div_number(matrix1: Matrix, number: int | float):
    assert (
        (np.array((matrix1 / number).matrix) == np.array(matrix1.matrix) / number).all()
    ), 'div section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2.T()]])    
def test_matrix_matmul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert(
        (np.array((matrix1 @ matrix2).matrix) == np.array(matrix1.matrix) @ np.array(matrix2.matrix)).all()
    ), 'matmul section is not working right, and don\'t forget about T() if needed'

print((matrix1*matrix2).matrix)
print(np.array(matrix1.matrix) * np.array(matrix2.matrix))


[[24, 30, 36], [24, 30, 36], [24, 30, 36]]
[[ 4 10 18]
 [ 4 10 18]
 [ 4 10 18]]
.F.F.F.F..                                                                                   [100%]
============================================ FAILURES =============================================
______________________________ test_matrix_add_number[matrix10-13.2] ______________________________

matrix1 = <__main__.Matrix object at 0x0000025BEB55D910>, number = 13.2

    @pytest.mark.parametrize("matrix1,number", [[matrix1, 13.2]])
    def test_matrix_add_number(matrix1: Matrix, number: int | float):
>       assert (
            (np.array((matrix1 + number).matrix) == np.array(matrix1.matrix) + number).all()
        ), 'add section with matrix and number is not working right'

C:\Users\Евгений\AppData\Local\Temp\ipykernel_6016\4192275343.py:14: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <__main__.Matrix object at 0x0000025BEB55D910>, othe