In [44]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import re


import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Евгений\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Евгений\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Евгений\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [45]:
with open('1.txt', 'r', encoding = 'utf-8') as book1:
    text1 = book1.read()

with open('2.txt', 'r', encoding = 'utf-8') as book2:
    text2 = book2.read()

with open('3.txt', 'r', encoding = 'utf-8') as book3:
    text3 = book3.read()

with open('4.txt', 'r', encoding = 'utf-8') as book4:
    text4 = book4.read()

with open('5.txt', 'r', encoding = 'utf-8') as book5:
    text5 = book5.read()

with open('6.txt', 'r', encoding = 'utf-8') as book6:
    text6 = book6.read()



In [46]:
def tokenize_and_lemmatize(text):
    lemmatizer = WordNetLemmatizer()  # Инициализация лемматизатора
    tokens = word_tokenize(text) 
    lemmatized_tokens = [lemmatizer.lemmatize(token.lower()) for token in tokens]
    return lemmatized_tokens

def compare_books(books):
    vectorizer = TfidfVectorizer(tokenizer=tokenize_and_lemmatize)
    X = vectorizer.fit_transform(books)

    similarities = cosine_similarity(X)

    return similarities


In [47]:
book_texts = [text1, text2, text3, text4, text5, text6]
similarity_matrix = compare_books(book_texts)
print("Матрица косинусового сходства книг:")
print(similarity_matrix)


Матрица косинусового сходства книг:
[[1.         0.76003856 0.79194842 0.8011656  0.79145189 0.66521058]
 [0.76003856 1.         0.95704927 0.88295605 0.93266726 0.89527047]
 [0.79194842 0.95704927 1.         0.92904367 0.98440795 0.89132534]
 [0.8011656  0.88295605 0.92904367 1.         0.93670656 0.79395481]
 [0.79145189 0.93266726 0.98440795 0.93670656 1.         0.86515372]
 [0.66521058 0.89527047 0.89132534 0.79395481 0.86515372 1.        ]]
